<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jarak_desa extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_jarak_desa_model');
    } 

    /*
     * Listing of tb_jarak_desa
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tb_jarak_desa/index?');
        $config['total_rows'] = $this->Tb_jarak_desa_model->get_all_tb_jarak_desa_count();
        $this->pagination->initialize($config);

        $data['tb_jarak_desa'] = $this->Tb_jarak_desa_model->get_all_tb_jarak_desa($params);
        
        $this->load->template('tb_jarak_desa/index',$data);
    }

    /*
     * Adding a new tb_jarak_desa
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('jarak','Jarak','integer');
		$this->form_validation->set_rules('tahun','Tahun','integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_desa_awal' => $this->input->post('id_desa_awal'),
				'id_desa_akhir' => $this->input->post('id_desa_akhir'),
				'jarak' => $this->input->post('jarak'),
				'tahun' => $this->input->post('tahun'),
            );
            
            $tb_jarak_desa_id = $this->Tb_jarak_desa_model->add_tb_jarak_desa($params);
            redirect('jarak_desa/index');
        }
        else
        {            
            $this->load->template('tb_jarak_desa/add');
        }
    }  

    /*
     * Editing a tb_jarak_desa
     */
    function edit($id)
    {   
        // check if the tb_jarak_desa exists before trying to edit it
        $data['tb_jarak_desa'] = $this->Tb_jarak_desa_model->get_tb_jarak_desa($id);
        
        if(isset($data['tb_jarak_desa']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('jarak','Jarak','integer');
			$this->form_validation->set_rules('tahun','Tahun','integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_desa_awal' => $this->input->post('id_desa_awal'),
					'id_desa_akhir' => $this->input->post('id_desa_akhir'),
					'jarak' => $this->input->post('jarak'),
					'tahun' => $this->input->post('tahun'),
                );

                $this->Tb_jarak_desa_model->update_tb_jarak_desa($id,$params);            
                redirect('jarak_desa/index');
            }
            else
            {
                $this->load->template('tb_jarak_desa/edit',$data);
            }
        }
        else
            show_error('The tb_jarak_desa you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_jarak_desa
     */
    function remove($id)
    {
        $tb_jarak_desa = $this->Tb_jarak_desa_model->get_tb_jarak_desa($id);

        // check if the tb_jarak_desa exists before trying to delete it
        if(isset($tb_jarak_desa['id']))
        {
            $this->Tb_jarak_desa_model->delete_tb_jarak_desa($id);
            redirect('jarak_desa/index');
        }
        else
            show_error('The tb_jarak_desa you are trying to delete does not exist.');
    }
    
}
