<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kependudukan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_kependudukan_model');
    } 

    /*
     * Listing of tb_kependudukan
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tb_kependudukan/index?');
        $config['total_rows'] = $this->Tb_kependudukan_model->get_all_tb_kependudukan_count();
        $this->pagination->initialize($config);

        $data['tb_kependudukan'] = $this->Tb_kependudukan_model->get_all_tb_kependudukan($params);
        
        $this->load->template('tb_kependudukan/index',$data);
    }

    /*
     * Adding a new tb_kependudukan
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_desa' => $this->input->post('id_desa'),
				'laki_laki' => $this->input->post('laki_laki'),
				'perempuan' => $this->input->post('perempuan'),
				'tahun' => $this->input->post('tahun'),
            );
            
            $tb_kependudukan_id = $this->Tb_kependudukan_model->add_tb_kependudukan($params);
            redirect('kependudukan/index');
        }
        else
        {            
            $this->load->template('tb_kependudukan/add');
        }
    }  

    /*
     * Editing a tb_kependudukan
     */
    function edit($id)
    {   
        // check if the tb_kependudukan exists before trying to edit it
        $data['tb_kependudukan'] = $this->Tb_kependudukan_model->get_tb_kependudukan($id);
        
        if(isset($data['tb_kependudukan']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_desa' => $this->input->post('id_desa'),
					'laki_laki' => $this->input->post('laki_laki'),
					'perempuan' => $this->input->post('perempuan'),
					'tahun' => $this->input->post('tahun'),
                );

                $this->Tb_kependudukan_model->update_tb_kependudukan($id,$params);            
                redirect('kependudukan/index');
            }
            else
            {
                $this->load->template('tb_kependudukan/edit',$data);
            }
        }
        else
            show_error('The tb_kependudukan you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_kependudukan
     */
    function remove($id)
    {
        $tb_kependudukan = $this->Tb_kependudukan_model->get_tb_kependudukan($id);

        // check if the tb_kependudukan exists before trying to delete it
        if(isset($tb_kependudukan['id']))
        {
            $this->Tb_kependudukan_model->delete_tb_kependudukan($id);
            redirect('kependudukan/index');
        }
        else
            show_error('The tb_kependudukan you are trying to delete does not exist.');
    }
    
}
