<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Luas_wilayah extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_luas_wilayah_model');
    } 

    /*
     * Listing of tb_luas_wilayah
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tb_luas_wilayah/index?');
        $config['total_rows'] = $this->Tb_luas_wilayah_model->get_all_tb_luas_wilayah_count();
        $this->pagination->initialize($config);

        $data['tb_luas_wilayah'] = $this->Tb_luas_wilayah_model->get_all_tb_luas_wilayah($params);
        
        $this->load->template('tb_luas_wilayah/index',$data);
    }

    /*
     * Adding a new tb_luas_wilayah
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_desa' => $this->input->post('id_desa'),
				'luas_wilayah' => $this->input->post('luas_wilayah'),
				'tanah_sawah' => $this->input->post('tanah_sawah'),
				'tanah_kering' => $this->input->post('tanah_kering'),
				'tahun' => $this->input->post('tahun'),
            );
            
            $tb_luas_wilayah_id = $this->Tb_luas_wilayah_model->add_tb_luas_wilayah($params);
            redirect('luas_wilayah/index');
        }
        else
        {            
            $this->load->template('tb_luas_wilayah/add');
        }
    }  

    /*
     * Editing a tb_luas_wilayah
     */
    function edit($id)
    {   
        // check if the tb_luas_wilayah exists before trying to edit it
        $data['tb_luas_wilayah'] = $this->Tb_luas_wilayah_model->get_tb_luas_wilayah($id);
        
        if(isset($data['tb_luas_wilayah']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_desa' => $this->input->post('id_desa'),
					'luas_wilayah' => $this->input->post('luas_wilayah'),
					'tanah_sawah' => $this->input->post('tanah_sawah'),
					'tanah_kering' => $this->input->post('tanah_kering'),
					'tahun' => $this->input->post('tahun'),
                );

                $this->Tb_luas_wilayah_model->update_tb_luas_wilayah($id,$params);            
                redirect('luas_wilayah/index');
            }
            else
            {
                $this->load->template('tb_luas_wilayah/edit',$data);
            }
        }
        else
            show_error('The tb_luas_wilayah you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_luas_wilayah
     */
    function remove($id)
    {
        $tb_luas_wilayah = $this->Tb_luas_wilayah_model->get_tb_luas_wilayah($id);

        // check if the tb_luas_wilayah exists before trying to delete it
        if(isset($tb_luas_wilayah['id']))
        {
            $this->Tb_luas_wilayah_model->delete_tb_luas_wilayah($id);
            redirect('luas_wilayah/index');
        }
        else
            show_error('The tb_luas_wilayah you are trying to delete does not exist.');
    }
    
}
