<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mutasi_kependudukan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_mutasi_kependudukan_model');
    } 

    /*
     * Listing of tb_mutasi_kependudukan
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tb_mutasi_kependudukan/index?');
        $config['total_rows'] = $this->Tb_mutasi_kependudukan_model->get_all_tb_mutasi_kependudukan_count();
        $this->pagination->initialize($config);

        $data['tb_mutasi_kependudukan'] = $this->Tb_mutasi_kependudukan_model->get_all_tb_mutasi_kependudukan($params);
        
        $this->load->template('tb_mutasi_kependudukan/index',$data);
    }

    /*
     * Adding a new tb_mutasi_kependudukan
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_desa' => $this->input->post('id_desa'),
				'jenis_mutasi' => $this->input->post('jenis_mutasi'),
				'jenis_kelamin' => $this->input->post('jenis_kelamin'),
				'jumlah' => $this->input->post('jumlah'),
				'tahun' => $this->input->post('tahun'),
            );
            
            $tb_mutasi_kependudukan_id = $this->Tb_mutasi_kependudukan_model->add_tb_mutasi_kependudukan($params);
            redirect('mutasi_kependudukan/index');
        }
        else
        {            
            $this->load->template('tb_mutasi_kependudukan/add');
        }
    }  

    /*
     * Editing a tb_mutasi_kependudukan
     */
    function edit($id)
    {   
        // check if the tb_mutasi_kependudukan exists before trying to edit it
        $data['tb_mutasi_kependudukan'] = $this->Tb_mutasi_kependudukan_model->get_tb_mutasi_kependudukan($id);
        
        if(isset($data['tb_mutasi_kependudukan']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_desa' => $this->input->post('id_desa'),
					'jenis_mutasi' => $this->input->post('jenis_mutasi'),
					'jenis_kelamin' => $this->input->post('jenis_kelamin'),
					'jumlah' => $this->input->post('jumlah'),
					'tahun' => $this->input->post('tahun'),
                );

                $this->Tb_mutasi_kependudukan_model->update_tb_mutasi_kependudukan($id,$params);            
                redirect('mutasi_kependudukan/index');
            }
            else
            {
                $this->load->template('tb_mutasi_kependudukan/edit',$data);
            }
        }
        else
            show_error('The tb_mutasi_kependudukan you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_mutasi_kependudukan
     */
    function remove($id)
    {
        $tb_mutasi_kependudukan = $this->Tb_mutasi_kependudukan_model->get_tb_mutasi_kependudukan($id);

        // check if the tb_mutasi_kependudukan exists before trying to delete it
        if(isset($tb_mutasi_kependudukan['id']))
        {
            $this->Tb_mutasi_kependudukan_model->delete_tb_mutasi_kependudukan($id);
            redirect('mutasi_kependudukan/index');
        }
        else
            show_error('The tb_mutasi_kependudukan you are trying to delete does not exist.');
    }
    
}
