<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Panen_produksi extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_panen_produksi_model');
    } 

    /*
     * Listing of tb_panen_produksi
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tb_panen_produksi/index?');
        $config['total_rows'] = $this->Tb_panen_produksi_model->get_all_tb_panen_produksi_count();
        $this->pagination->initialize($config);

        $data['tb_panen_produksi'] = $this->Tb_panen_produksi_model->get_all_tb_panen_produksi($params);

        $this->load->template('tb_panen_produksi/index',$data);
    }

    /*
     * Adding a new tb_panen_produksi
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_desa' => $this->input->post('id_desa'),
				'id' => $this->input->post('id'),
				'kuas_panen' => $this->input->post('kuas_panen'),
				'rata_rata_produksi' => $this->input->post('rata_rata_produksi'),
				'produksi' => $this->input->post('produksi'),
            );
            
            $tb_panen_produksi_id = $this->Tb_panen_produksi_model->add_tb_panen_produksi($params);
            redirect('panen_produksi/index');
        }
        else
        {            
            $this->load->template('tb_panen_produksi/add');
        }
    }  

    /*
     * Editing a tb_panen_produksi
     */
    function edit($id)
    {   
        // check if the tb_panen_produksi exists before trying to edit it
        $data['tb_panen_produksi'] = $this->Tb_panen_produksi_model->get_tb_panen_produksi($id);
        
        if(isset($data['tb_panen_produksi']['']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_desa' => $this->input->post('id_desa'),
					'id' => $this->input->post('id'),
					'kuas_panen' => $this->input->post('kuas_panen'),
					'rata_rata_produksi' => $this->input->post('rata_rata_produksi'),
					'produksi' => $this->input->post('produksi'),
                );

                $this->Tb_panen_produksi_model->update_tb_panen_produksi($id,$params);            
                redirect('panen_produksi/index');
            }
            else
            {

                $this->load->template('tb_panen_produksi/edit',$data);
            }
        }
        else
            show_error('The tb_panen_produksi you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_panen_produksi
     */
    function remove($id)
    {
        $tb_panen_produksi = $this->Tb_panen_produksi_model->get_tb_panen_produksi($id);

        // check if the tb_panen_produksi exists before trying to delete it
        if(isset($tb_panen_produksi['']))
        {
            $this->Tb_panen_produksi_model->delete_tb_panen_produksi($id);
            redirect('panen_produksi/index');
        }
        else
            show_error('The tb_panen_produksi you are trying to delete does not exist.');
    }
    
}
