<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pln_pdam extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_pln_pdam_model');
    } 

    /*
     * Listing of tb_pln_pdam
     */
    function index()
    {
        $data['tb_pln_pdam'] = $this->Tb_pln_pdam_model->get_all_tb_pln_pdam();
        
        $this->load->template('tb_pln_pdam/index',$data);
    }

    /*
     * Adding a new tb_pln_pdam
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_desa' => $this->input->post('id_desa'),
				'id' => $this->input->post('id'),
				'rumah_tangga' => $this->input->post('rumah_tangga'),
				'pelanggan_pln' => $this->input->post('pelanggan_pln'),
				'pelanggan_pdam' => $this->input->post('pelanggan_pdam'),
				'tahun' => $this->input->post('tahun'),
            );
            
            $tb_pln_pdam_id = $this->Tb_pln_pdam_model->add_tb_pln_pdam($params);
            redirect('pln_pdam/index');
        }
        else
        {            
            $this->load->template('tb_pln_pdam/add');
        }
    }  

    /*
     * Editing a tb_pln_pdam
     */
    function edit($id)
    {   
        // check if the tb_pln_pdam exists before trying to edit it
        $data['tb_pln_pdam'] = $this->Tb_pln_pdam_model->get_tb_pln_pdam($id);
        
        if(isset($data['tb_pln_pdam']['']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_desa' => $this->input->post('id_desa'),
					'id' => $this->input->post('id'),
					'rumah_tangga' => $this->input->post('rumah_tangga'),
					'pelanggan_pln' => $this->input->post('pelanggan_pln'),
					'pelanggan_pdam' => $this->input->post('pelanggan_pdam'),
					'tahun' => $this->input->post('tahun'),
                );

                $this->Tb_pln_pdam_model->update_tb_pln_pdam($id,$params);            
                redirect('pln_pdam/index');
            }
            else
            {
                $this->load->template('tb_pln_pdam/edit',$data);
            }
        }
        else
            show_error('The tb_pln_pdam you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_pln_pdam
     */
    function remove($id)
    {
        $tb_pln_pdam = $this->Tb_pln_pdam_model->get_tb_pln_pdam($id);

        // check if the tb_pln_pdam exists before trying to delete it
        if(isset($tb_pln_pdam['']))
        {
            $this->Tb_pln_pdam_model->delete_tb_pln_pdam($id);
            redirect('pln_pdam/index');
        }
        else
            show_error('The tb_pln_pdam you are trying to delete does not exist.');
    }
    
}
