<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tanah_bengkok extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_tanah_bengkok_model');
    } 

    /*
     * Listing of tb_tanah_bengkok
     */
    function index()
    {
        $data['tb_tanah_bengkok'] = $this->Tb_tanah_bengkok_model->get_all_tb_tanah_bengkok();
        
        $this->load->template('tb_tanah_bengkok/index',$data);
    }

    /*
     * Adding a new tb_tanah_bengkok
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_desa' => $this->input->post('id_desa'),
				'bengkok_sawah' => $this->input->post('bengkok_sawah'),
				'bengkok_lahan_kering' => $this->input->post('bengkok_lahan_kering'),
				'kas_sawah' => $this->input->post('kas_sawah'),
				'kas_lahan_kering' => $this->input->post('kas_lahan_kering'),
				'tahun' => $this->input->post('tahun'),
            );
            
            $tb_tanah_bengkok_id = $this->Tb_tanah_bengkok_model->add_tb_tanah_bengkok($params);
            redirect('tanah_bengkok/index');
        }
        else
        {            
            $this->load->template('tb_tanah_bengkok/add');
        }
    }  

    /*
     * Editing a tb_tanah_bengkok
     */
    function edit($id)
    {   
        // check if the tb_tanah_bengkok exists before trying to edit it
        $data['tb_tanah_bengkok'] = $this->Tb_tanah_bengkok_model->get_tb_tanah_bengkok($id);
        
        if(isset($data['tb_tanah_bengkok']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_desa' => $this->input->post('id_desa'),
					'bengkok_sawah' => $this->input->post('bengkok_sawah'),
					'bengkok_lahan_kering' => $this->input->post('bengkok_lahan_kering'),
					'kas_sawah' => $this->input->post('kas_sawah'),
					'kas_lahan_kering' => $this->input->post('kas_lahan_kering'),
					'tahun' => $this->input->post('tahun'),
                );

                $this->Tb_tanah_bengkok_model->update_tb_tanah_bengkok($id,$params);            
                redirect('tanah_bengkok/index');
            }
            else
            {
                $this->load->template('tb_tanah_bengkok/edit',$data);
            }
        }
        else
            show_error('The tb_tanah_bengkok you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_tanah_bengkok
     */
    function remove($id)
    {
        $tb_tanah_bengkok = $this->Tb_tanah_bengkok_model->get_tb_tanah_bengkok($id);

        // check if the tb_tanah_bengkok exists before trying to delete it
        if(isset($tb_tanah_bengkok['id']))
        {
            $this->Tb_tanah_bengkok_model->delete_tb_tanah_bengkok($id);
            redirect('tanah_bengkok/index');
        }
        else
            show_error('The tb_tanah_bengkok you are trying to delete does not exist.');
    }
    
}
