<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tr_kependudukan_umur extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tr_kependudukan_umur_model');
    } 

    /*
     * Listing of tr_kependudukan_umur
     */
    function index()
    {
        $data['tr_kependudukan_umur'] = $this->Tr_kependudukan_umur_model->get_all_tr_kependudukan_umur();
        
        $data['_view'] = 'tr_kependudukan_umur/index';
        $this->load->template('layouts/main',$data);
    }

    /*
     * Adding a new tr_kependudukan_umur
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_kependudukan' => $this->input->post('id_kependudukan'),
				'umur' => $this->input->post('umur'),
				'jenis_kelamin' => $this->input->post('jenis_kelamin'),
				'jumlah' => $this->input->post('jumlah'),
            );
            
            $tr_kependudukan_umur_id = $this->Tr_kependudukan_umur_model->add_tr_kependudukan_umur($params);
            redirect('tr_kependudukan_umur/index');
        }
        else
        {            
            $this->load->template('tr_kependudukan_umur/add');
        }
    }  

    /*
     * Editing a tr_kependudukan_umur
     */
    function edit($id)
    {   
        // check if the tr_kependudukan_umur exists before trying to edit it
        $data['tr_kependudukan_umur'] = $this->Tr_kependudukan_umur_model->get_tr_kependudukan_umur($id);
        
        if(isset($data['tr_kependudukan_umur']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_kependudukan' => $this->input->post('id_kependudukan'),
					'umur' => $this->input->post('umur'),
					'jenis_kelamin' => $this->input->post('jenis_kelamin'),
					'jumlah' => $this->input->post('jumlah'),
                );

                $this->Tr_kependudukan_umur_model->update_tr_kependudukan_umur($id,$params);            
                redirect('tr_kependudukan_umur/index');
            }
            else
            {
                $this->load->template('tr_kependudukan_umur/edit',$data);
            }
        }
        else
            show_error('The tr_kependudukan_umur you are trying to edit does not exist.');
    } 

    /*
     * Deleting tr_kependudukan_umur
     */
    function remove($id)
    {
        $tr_kependudukan_umur = $this->Tr_kependudukan_umur_model->get_tr_kependudukan_umur($id);

        // check if the tr_kependudukan_umur exists before trying to delete it
        if(isset($tr_kependudukan_umur['id']))
        {
            $this->Tr_kependudukan_umur_model->delete_tr_kependudukan_umur($id);
            redirect('tr_kependudukan_umur/index');
        }
        else
            show_error('The tr_kependudukan_umur you are trying to delete does not exist.');
    }
    
}
