<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tr_luas_tanah_kering extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tr_luas_tanah_kering_model');
    } 

    /*
     * Listing of tr_luas_tanah_kering
     */
    function index()
    {
        $data['tr_luas_tanah_kering'] = $this->Tr_luas_tanah_kering_model->get_all_tr_luas_tanah_kering();
        
        $this->load->template('tr_luas_tanah_kering/index',$data);
    }

    /*
     * Adding a new tr_luas_tanah_kering
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_luas_wilayah' => $this->input->post('id_luas_wilayah'),
				'perkarangan_bangunan' => $this->input->post('perkarangan_bangunan'),
				'tegal_kebun' => $this->input->post('tegal_kebun'),
				'padang_gembala' => $this->input->post('padang_gembala'),
				'tambak_kolam' => $this->input->post('tambak_kolam'),
				'hutan_negara' => $this->input->post('hutan_negara'),
				'perkebunan_negara' => $this->input->post('perkebunan_negara'),
				'lainnya' => $this->input->post('lainnya'),
            );
            
            $tr_luas_tanah_kering_id = $this->Tr_luas_tanah_kering_model->add_tr_luas_tanah_kering($params);
            redirect('tr_luas_tanah_kering/index');
        }
        else
        {            
            $this->load->template('tr_luas_tanah_kering/add');
        }
    }  

    /*
     * Editing a tr_luas_tanah_kering
     */
    function edit($id)
    {   
        // check if the tr_luas_tanah_kering exists before trying to edit it
        $data['tr_luas_tanah_kering'] = $this->Tr_luas_tanah_kering_model->get_tr_luas_tanah_kering($id);
        
        if(isset($data['tr_luas_tanah_kering']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_luas_wilayah' => $this->input->post('id_luas_wilayah'),
					'perkarangan_bangunan' => $this->input->post('perkarangan_bangunan'),
					'tegal_kebun' => $this->input->post('tegal_kebun'),
					'padang_gembala' => $this->input->post('padang_gembala'),
					'tambak_kolam' => $this->input->post('tambak_kolam'),
					'hutan_negara' => $this->input->post('hutan_negara'),
					'perkebunan_negara' => $this->input->post('perkebunan_negara'),
					'lainnya' => $this->input->post('lainnya'),
                );

                $this->Tr_luas_tanah_kering_model->update_tr_luas_tanah_kering($id,$params);            
                redirect('tr_luas_tanah_kering/index');
            }
            else
            {
                $this->load->template('tr_luas_tanah_kering/edit',$data);
            }
        }
        else
            show_error('The tr_luas_tanah_kering you are trying to edit does not exist.');
    } 

    /*
     * Deleting tr_luas_tanah_kering
     */
    function remove($id)
    {
        $tr_luas_tanah_kering = $this->Tr_luas_tanah_kering_model->get_tr_luas_tanah_kering($id);

        // check if the tr_luas_tanah_kering exists before trying to delete it
        if(isset($tr_luas_tanah_kering['id']))
        {
            $this->Tr_luas_tanah_kering_model->delete_tr_luas_tanah_kering($id);
            redirect('tr_luas_tanah_kering/index');
        }
        else
            show_error('The tr_luas_tanah_kering you are trying to delete does not exist.');
    }
    
}
