<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_desa_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_desa by id_desa
     */
    function get_tb_desa($id_desa)
    {
        return $this->db->get_where('tb_desa',array('id_desa'=>$id_desa))->row_array();
    }
        
    /*
     * Get all tb_desa
     */
    function get_all_tb_desa()
    {
        $this->db->order_by('id_desa', 'desc');
        return $this->db->get('tb_desa')->result_array();
    }
        
    /*
     * function to add new tb_desa
     */
    function add_tb_desa($params)
    {
        $this->db->insert('tb_desa',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_desa
     */
    function update_tb_desa($id_desa,$params)
    {
        $this->db->where('id_desa',$id_desa);
        return $this->db->update('tb_desa',$params);
    }
    
    /*
     * function to delete tb_desa
     */
    function delete_tb_desa($id_desa)
    {
        return $this->db->delete('tb_desa',array('id_desa'=>$id_desa));
    }
}
