<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_kependudukan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_kependudukan by id
     */
    function get_tb_kependudukan($id)
    {
        return $this->db->get_where('tb_kependudukan',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all tb_kependudukan count
     */
    function get_all_tb_kependudukan_count()
    {
        $this->db->from('tb_kependudukan');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tb_kependudukan
     */
    function get_all_tb_kependudukan($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_kependudukan')->result_array();
    }
        
    /*
     * function to add new tb_kependudukan
     */
    function add_tb_kependudukan($params)
    {
        $this->db->insert('tb_kependudukan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_kependudukan
     */
    function update_tb_kependudukan($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tb_kependudukan',$params);
    }
    
    /*
     * function to delete tb_kependudukan
     */
    function delete_tb_kependudukan($id)
    {
        return $this->db->delete('tb_kependudukan',array('id'=>$id));
    }
}
