<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_luas_wilayah_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_luas_wilayah by id
     */
    function get_tb_luas_wilayah($id)
    {
        return $this->db->get_where('tb_luas_wilayah',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all tb_luas_wilayah count
     */
    function get_all_tb_luas_wilayah_count()
    {
        $this->db->from('tb_luas_wilayah');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tb_luas_wilayah
     */
    function get_all_tb_luas_wilayah($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_luas_wilayah')->result_array();
    }
        
    /*
     * function to add new tb_luas_wilayah
     */
    function add_tb_luas_wilayah($params)
    {
        $this->db->insert('tb_luas_wilayah',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_luas_wilayah
     */
    function update_tb_luas_wilayah($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tb_luas_wilayah',$params);
    }
    
    /*
     * function to delete tb_luas_wilayah
     */
    function delete_tb_luas_wilayah($id)
    {
        return $this->db->delete('tb_luas_wilayah',array('id'=>$id));
    }
}
