<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_mutasi_kependudukan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_mutasi_kependudukan by id
     */
    function get_tb_mutasi_kependudukan($id)
    {
        return $this->db->get_where('tb_mutasi_kependudukan',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all tb_mutasi_kependudukan count
     */
    function get_all_tb_mutasi_kependudukan_count()
    {
        $this->db->from('tb_mutasi_kependudukan');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tb_mutasi_kependudukan
     */
    function get_all_tb_mutasi_kependudukan($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_mutasi_kependudukan')->result_array();
    }
        
    /*
     * function to add new tb_mutasi_kependudukan
     */
    function add_tb_mutasi_kependudukan($params)
    {
        $this->db->insert('tb_mutasi_kependudukan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_mutasi_kependudukan
     */
    function update_tb_mutasi_kependudukan($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tb_mutasi_kependudukan',$params);
    }
    
    /*
     * function to delete tb_mutasi_kependudukan
     */
    function delete_tb_mutasi_kependudukan($id)
    {
        return $this->db->delete('tb_mutasi_kependudukan',array('id'=>$id));
    }
}
