<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_pln_pdam_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_pln_pdam by 
     */
    function get_tb_pln_pdam($id)
    {
        return $this->db->get_where('tb_pln_pdam',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tb_pln_pdam
     */
    function get_all_tb_pln_pdam()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('tb_pln_pdam')->result_array();
    }
        
    /*
     * function to add new tb_pln_pdam
     */
    function add_tb_pln_pdam($params)
    {
        $this->db->insert('tb_pln_pdam',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_pln_pdam
     */
    function update_tb_pln_pdam($id,$params)
    {
        $this->db->where('',$id);
        return $this->db->update('tb_pln_pdam',$params);
    }
    
    /*
     * function to delete tb_pln_pdam
     */
    function delete_tb_pln_pdam($id)
    {
        return $this->db->delete('tb_pln_pdam',array('id'=>$id));
    }
}
