<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_panen_produksi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_panen_produksi by 
     */
    function get_tb_panen_produksi($id)
    {
        return $this->db->get_where('tb_panen_produksi',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all tb_panen_produksi count
     */
    function get_all_tb_panen_produksi_count()
    {
        $this->db->from('tb_panen_produksi');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tb_panen_produksi
     */
    function get_all_tb_panen_produksi($params = array())
    {
        $this->db->order_by('', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_panen_produksi')->result_array();
    }
        
    /*
     * function to add new tb_panen_produksi
     */
    function add_tb_panen_produksi($params)
    {
        $this->db->insert('tb_panen_produksi',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_panen_produksi
     */
    function update_tb_panen_produksi($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tb_panen_produksi',$params);
    }
    
    /*
     * function to delete tb_panen_produksi
     */
    function delete_tb_panen_produksi($id)
    {
        return $this->db->delete('tb_panen_produksi',array('id'=>$id));
    }
}
