<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_tanah_bengkok_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_tanah_bengkok by id
     */
    function get_tb_tanah_bengkok($id)
    {
        return $this->db->get_where('tb_tanah_bengkok',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tb_tanah_bengkok
     */
    function get_all_tb_tanah_bengkok()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tb_tanah_bengkok')->result_array();
    }
        
    /*
     * function to add new tb_tanah_bengkok
     */
    function add_tb_tanah_bengkok($params)
    {
        $this->db->insert('tb_tanah_bengkok',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_tanah_bengkok
     */
    function update_tb_tanah_bengkok($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tb_tanah_bengkok',$params);
    }
    
    /*
     * function to delete tb_tanah_bengkok
     */
    function delete_tb_tanah_bengkok($id)
    {
        return $this->db->delete('tb_tanah_bengkok',array('id'=>$id));
    }
}
